export const SCORE_CHECKER_V2_ABI = [
  // Legacy functions for backward compatibility
  {
    inputs: [
      { name: "score", type: "uint256" },
      { name: "issuedAt", type: "uint64" },
      { name: "nonce", type: "uint256" },
      { name: "signature", type: "bytes" },
    ],
    name: "submitScore",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "checkFee",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "user", type: "address" }],
    name: "getUserData",
    outputs: [
      { name: "score", type: "uint256" },
      { name: "lastCheckTime", type: "uint256" },
      { name: "lastIssuedAt", type: "uint256" },
      { name: "nonce", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "user", type: "address" }],
    name: "getScore",
    outputs: [
      { name: "score", type: "uint256" },
      { name: "timestamp", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "user", type: "address" }],
    name: "canSubmitScore",
    outputs: [
      { name: "canSubmit", type: "bool" },
      { name: "timeRemaining", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  
  // New V2 functions
  {
    inputs: [
      { name: "totalScore", type: "uint256" },
      { name: "baseScore", type: "uint256" },
      { name: "securityScore", type: "uint256" },
      { name: "numberOfTransactions", type: "uint256" },
      { name: "currentStreak", type: "uint256" },
      { name: "maxStreak", type: "uint256" },
      { name: "currentBalance", type: "uint256" },
      { name: "avgBalanceLastMonth", type: "uint256" },
      { name: "gasPaid", type: "uint256" },
      { name: "suspiciousTokens", type: "uint256" },
      { name: "suspiciousContracts", type: "uint256" },
      { name: "dangerousInteractions", type: "uint256" },
      { name: "suspiciousOilCompanies", type: "uint256" },
      { name: "issuedAt", type: "uint64" },
      { name: "nonce", type: "uint256" },
      { name: "signature", type: "bytes" },
    ],
    name: "submitScoreCard",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ name: "user", type: "address" }],
    name: "getScoreCard",
    outputs: [
      { name: "totalScore", type: "uint256" },
      { name: "baseScore", type: "uint256" },
      { name: "securityScore", type: "uint256" },
      { name: "numberOfTransactions", type: "uint256" },
      { name: "currentStreak", type: "uint256" },
      { name: "maxStreak", type: "uint256" },
      { name: "currentBalance", type: "uint256" },
      { name: "avgBalanceLastMonth", type: "uint256" },
      { name: "gasPaid", type: "uint256" },
      { name: "suspiciousTokens", type: "uint256" },
      { name: "suspiciousContracts", type: "uint256" },
      { name: "dangerousInteractions", type: "uint256" },
      { name: "suspiciousOilCompanies", type: "uint256" },
      { name: "lastCheckTime", type: "uint256" },
      { name: "lastIssuedAt", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "structHash", type: "bytes32" }],
    name: "hashTypedDataV4",
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  
  // Admin functions
  {
    inputs: [{ name: "_signer", type: "address" }],
    name: "setAuthorizedSigner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_newFee", type: "uint256" }],
    name: "setCheckFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_seconds", type: "uint256" }],
    name: "setMinInterval",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_seconds", type: "uint256" }],
    name: "setMaxSigAge",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "to", type: "address" }],
    name: "withdrawFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  
  // View functions
  {
    inputs: [],
    name: "authorizedSigner",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "minInterval",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxSigAge",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "address" }],
    name: "nonces",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_FEE",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_SCORE",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_ISSUED_AT",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_INTERVAL",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DEFAULT_MAX_SIG_AGE",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  
  // Events
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "totalScore", type: "uint256" },
      { indexed: false, name: "fee", type: "uint256" },
      { indexed: false, name: "timestamp", type: "uint256" },
    ],
    name: "ScoreCardUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "score", type: "uint256" },
      { indexed: false, name: "fee", type: "uint256" },
      { indexed: false, name: "timestamp", type: "uint256" },
    ],
    name: "ScoreChecked",
    type: "event",
  },
  
  // Fallback and receive
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];
